export const APP_LOADING = 'APP_LOADING'
export const APP_READY = 'APP_READY'
export const APP_ERROR = 'APP_ERROR'
export const APP_ERRORS_CLEAR = 'APP_ERRORS_CLEAR'

export const USER_SIGNED_IN = 'USER_SIGNED_IN'
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT'
export const USER_SIGNED_UP = 'USER_SIGNED_UP'

export const FETCHED_POLLS = 'FETCHED_POLLS'
export const SUBSCRIBED_TO_POLLS_SERVICE = 'SUBSCRIBED_TO_POLLS_SERVICE'
export const POLL_CREATED = 'POLL_CREATED'
export const POLL_UPDATED = 'POLL_UPDATED'
export const POLL_REMOVED = 'POLL_REMOVED'
